### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by williamty** [kurowasan/GraN-DAG#7]
After installed Singularity, I changed the start_example.sh setting, and put DAG1.npy ... files to a path. But here's what I get:

```
$ sudo sh start_example.sh
No GPU automatically detected. Setting SETTINGS.GPU to 0, and SETTINGS.NJOBS to cpu_count.
sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
Traceback (most recent call last):
  File "main.py", line 133, in <module>
    main(parser.parse_args())
  File "/code/gran_dag/main.py", line 87, in main
    normalize=opt.normalize_data, random_seed=opt.random_seed)
  File "/code/gran_dag/data.py", line 43, in __init__
    adjacency = np.load(os.path.join(file_path, "DAG{}.npy".format(i_dataset)))
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/GraN-DAG/dataset/DAG1.npy'

$ ls -l /home/xxx/GraN-DAG/dataset/DAG1.npy
-rw-r--r-- 1 xxx xxx 80128 May  4 08:49 /home/xxx/GraN-DAG/dataset/DAG1.npy
```
It seems to find data in the docker, cause I dont have python3.7 in my ubuntu.
How to deal with that?

**Comment by williamty** [comment]
OK, no one answers, so I figured it out myself....

The problem is caused by sudo. In my opinion, different users will bring different environment into the container. So, just not use sudo or put dataset somewhere everyone can fetch.
